sosfrene_admin/urls.py
"""
    Les routes
"""
from django.conf.urls import url

from sosfrene_admin.views import (
    TableauBordView, ConnexionView, DeconnexionView, SignalementsView,
    DetailsMessageView, DetailsSignalementView, TraiterSignalementView,
    SpecimensView, NouveauSpecimenView, MessagesView,
    ReponseMessageView, DetailsSpecimenView,
    SupprimerSpecimenView, NouvelleActiviteView, AdministrateursView
)


urlpatterns = [
    url(r'^$', TableauBordView.as_view(),
        name="tableau_bord"),
    url(r'^connexion/$', ConnexionView.as_view(),
        name="connexion"),
    url(r'^deconnexion/$', DeconnexionView.as_view(),
        name="deconnexion"),
    url(r'^signalements/$', SignalementsView.as_view(),
        name="signalements"),
    url(r'^signalements/(?P<signalement_id>[0-9]+)/$',
        DetailsSignalementView.as_view(),
        name="detailssignalement"),
    url(r'^signalements/(?P<signalement_id>[0-9]+)/traitement/$',
        TraiterSignalementView.as_view(),
        name="traiter_signalement"),
    url(r'^specimens/$', SpecimensView.as_view(),
        name="specimens"),
    url(r'^specimens/nouveau/$', NouveauSpecimenView.as_view(),
        name="nouveau_specimen"),
    url(r'^specimens/(?P<specimen_id>[0-9]+)/$',
        DetailsSpecimenView.as_view(), name="details_specimen"),
    url(r'^specimens/supprimer/(?P<specimen_id>[0-9]+)/$',
        SupprimerSpecimenView.as_view(), name="supprimer_specimen"),
    url(r'^messages/$', MessagesView.as_view(),
        name="messages"),
    url(r'^messages/(?P<message_id>[0-9]+)/$',
        DetailsMessageView.as_view(), name="details_message"),
    url(r'^messages/(?P<message_id>[0-9]+)/reponse/$',
        ReponseMessageView.as_view(), name="reponse"),
    url(r'^administrateurs/$', AdministrateursView.as_view(),
        name="gestion"),
    url(r'^specimens/(?P<specimen_id>[0-9]+)/nouvelle-activite/$', NouvelleActiviteView.as_view(),
        name="activite")
]

sosfrene_core/urls.py
"""
    Les routes
"""
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^admin/', include("sosfrene_admin.urls",
                            namespace="admin")),
    url(r'^', include("sosfrene_client.urls",
                       namespace="client")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sosfrene_admin/forms.py
from django import forms
from django.core.exceptions import ValidationError

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

from sosfrene_core.constants import ETATS_SPECIMEN
from sosfrene_core.api import courriel_existe
from sosfrene_client.forms import SpanRequiredForm


class EnregistrementForm(SpanRequiredForm):
    first_name = forms.CharField(label="Prénom", max_length=80, required=False)
    last_name = forms.CharField(label="Nom", max_length=80, required=False)
    email = forms.EmailField(label="Courriel", max_length=80, required=False)
    password = forms.CharField(label="Mot de passe", widget=forms.PasswordInput,
                               max_length=80, required=False)
    confirm_password = forms.CharField(
        label="Confirmez votre mot de passe",
        widget=forms.PasswordInput,
        max_length=80, required=False)

    def __init__(self, *args, **kwargs):
        super(EnregistrementForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'form-enregistrement'
        self.helper.form_method = 'post'
        self.helper.form_action = 'enregistrement'
        self.helper.add_input(Submit('submit', 'Créer un compte', css_class="btn-block"))
        self.helper.error_text_inline = False

    def clean_first_name(self):
        self.clean_required(self.cleaned_data["first_name"])
        return self.cleaned_data["first_name"]

    def clean_last_name(self):
        self.clean_required(self.cleaned_data["last_name"])
        return self.cleaned_data["last_name"]

    def clean_email(self):
        self.clean_required(self.cleaned_data["email"])
        if courriel_existe(self.cleaned_data["email"]):
            raise ValidationError("Cette adresse courriel est déjà utilisée.")
        return self.cleaned_data["email"]

    def clean_password(self):
        self.clean_required(self.cleaned_data["password"])
        return self.cleaned_data["password"]

    def clean_confirm_password(self):
        self.clean_required(self.cleaned_data["confirm_password"])

        if self.cleaned_data["password"] !=\
                self.cleaned_data["confirm_password"]:
            raise ValidationError('Les mots de passe doivent être identiques.')

        return self.cleaned_data["confirm_password"]


class TraiterSignalementForm(forms.Form):
    statut_specimen = forms.CharField(
        widget=forms.HiddenInput(), required=False)
    message = forms.CharField(
        widget=forms.Textarea, label="Message pour l'utilisateur:",
        max_length=1000, required=False)


class SpecimenForm(SpanRequiredForm):
    etat = forms.ChoiceField(
        label="État", choices=list(ETATS_SPECIMEN.items()), required=False)
    latitude = forms.FloatField(label="Latitude (-90 à 90)", required=False,
                                min_value=-90.0, max_value=90,
                                widget=forms.TextInput(
                                    attrs={'id': 'lat-input'}))
    longitude = forms.FloatField(label="Longitude (-180 à 180)", required=False,
                                 min_value=-180, max_value=180,
                                 widget=forms.TextInput(
                                     attrs={'id': 'lon-input'}))

    def __init__(self, *args, **kwargs):
        super(SpecimenForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'form-profil'
        self.helper.form_method = 'post'
        self.helper.add_input(Submit(
            'submit', 'Enregistrer', css_id="btn-ajouter-specimen",
            css_class="btn-large"))

    def clean_latitude(self):
        self.clean_required(self.cleaned_data["latitude"])
        return self.cleaned_data["latitude"]

    def clean_longitude(self):
        self.clean_required(self.cleaned_data["longitude"])
        return self.cleaned_data["longitude"]


class NouvelleActiviteForm(SpanRequiredForm):
    etat = forms.ChoiceField(
        label="État", choices=list(ETATS_SPECIMEN.items()), required=False)
    description = forms.CharField(
        widget=forms.Textarea, label="Description", max_length=500, required=False)

    def __init__(self, *args, **kwargs):
        super(NouvelleActiviteForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'form-activite'
        self.helper.form_method = 'post'
        self.helper.add_input(Submit(
            'submit', 'Soumettre', css_id="btn-ajouter-activite",
            css_class="btn-large"))

    def clean_latitude(self):
        self.clean_required(self.cleaned_data["description"])
        return self.cleaned_data["description"]

sosfrene_admin/views.py
from django.views import View
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.timezone import now

from sosfrene_client.forms import (
    ConnexionForm, MessageForm, SpanRequiredForm
)
from sosfrene_admin.forms import (
    EnregistrementForm, TraiterSignalementForm,
    SpecimenForm, NouvelleActiviteForm
)
from sosfrene_client.forms import MessageForm
from sosfrene_admin.constants import ADMIN_BASE, ADMIN_LOGIN_URL
from sosfrene_core.api import (
    messages_utilisateur, envoyer_message, creer_activite, ajouter_specimen
)
from sosfrene_core.constants import ETATS_SPECIMEN, ATTEINT
from sosfrene_core.models import (
    Utilisateur, Photo, Signalement, Message, Activite, Specimen, Localisation)


class AdminView(View):

    def get_context_data(self):
        context = {}
        context["menu_utilisateur"] = "sosfrene_admin/menu.html"
        context["route_base"] = "admin:"
        return context

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            utilisateur = Utilisateur.objects.get(user=request.user)
            if not utilisateur.admin:
                logout(request)
                redirect("admin:connexion")

        return super(AdminView, self).dispatch(request, *args, **kwargs)


class TableauBordView(LoginRequiredMixin, AdminView):
    login_url = ADMIN_LOGIN_URL

    def get(self, request):
        context = self.get_context_data()
        context["menu"] = "tableau"
        return render(
            request, ADMIN_BASE + "tableau_bord.html", context)


class AdministrateursView(LoginRequiredMixin, AdminView):
    login_url = ADMIN_LOGIN_URL

    def get(self, request):
        context = self.get_context_data()
        context["menu"] = "gestion"
        return render(
            request, ADMIN_BASE + "administrateurs.html", context)


class ConnexionView(AdminView):
    form_class = ConnexionForm
    initial = {}

    def get(self, request):
        if request.user.is_authenticated():
            return redirect("admin:tableau_bord")

        form = self.form_class(initial=self.initial)
        context = self.get_context_data()
        context["form"] = form
        return render(request, ADMIN_BASE + "connexion.html", context)

    def post(self, request):
        context = self.get_context_data()
        form = self.form_class(request.POST)
        context["form"] = form
        if form.is_valid():
            user = authenticate(username=form.cleaned_data["email"],
                                password=form.cleaned_data["password"])
            if user is not None:
                utilisateur = Utilisateur.objects.get(user=user)
                if utilisateur.admin:
                    login(request, user)
                    return redirect("admin:tableau_bord")
                else:
                    logout(request)
                    redirect("admin:connexion")
            else:
                context["erreur_mdp"] = True
                return render(
                    request, ADMIN_BASE + "connexion.html", context)

        return render(request, ADMIN_BASE + "connexion.html", context)


class DeconnexionView(View):

    def get(self, request):
        logout(request)
        return redirect("admin:connexion")


class SpecimensView(LoginRequiredMixin, AdminView):
    login_url = ADMIN_LOGIN_URL

    def get(self, request):
        context = self.get_context_data()
        specimens = list(Specimen.objects.all())
        context["specimens"] = specimens
        context["entetes"] = ["Localisation", "État", "Signalement"]
        context["menu"] = "specimens"
        return render(request, ADMIN_BASE + "specimens.html", context)


class NouveauSpecimenView(LoginRequiredMixin, AdminView):
    login_url = ADMIN_LOGIN_URL
    form_class = SpecimenForm
    initial = {}

    def get(self, request):
        context = self.get_context_data()
        form = self.form_class(initial=self.initial)
        context["form"] = form
        context["menu"] = "specimens"
        return render(request, ADMIN_BASE + "nouveau_specimen.html", context)

    def post(self, request):
        form = self.form_class(request.POST)
        context = self.get_context_data()
        context["menu"] = "specimens"
        context["form"] = form
        if form.is_valid():
            ajouter_specimen(form.cleaned_data["etat"],
                             form.cleaned_data["latitude"],
                             form.cleaned_data["longitude"])
            context["reussite"] = True
            form = self.form_class(initial=self.initial)
            context["form"] = form
            return render(request, ADMIN_BASE + "nouveau_specimen.html", context)

        return render(request, ADMIN_BASE + "nouveau_specimen.html", context)


class DetailsSpecimenView(LoginRequiredMixin, AdminView):
    login_url = ADMIN_LOGIN_URL
    form_class = SpecimenForm
    initial = {}

    def get(self, request, specimen_id):
        context = self.get_context_data()
        try:
            specimen = Specimen.objects.get(id=specimen_id)
        except Specimen.DoesNotExist:
            return redirect("admin:specimens")

        context["entetes"] = ["Date", "Nouvel état"]
        context["specimen"] = specimen
        activites = list(Activite.objects.filter(
            specimen__id=specimen.id).order_by("-date"))
        context["activites"] = activites
        context["menu"] = "specimens"
        self.initial["etat"] = specimen.etat
        self.initial["latitude"] = specimen.localisation.latitude
        self.initial["longitude"] = specimen.localisation.longitude
        form = self.form_class(initial=self.initial)
        context["form"] = form
        return render(request, ADMIN_BASE + "details_specimen.html", context)


class SupprimerSpecimenView(LoginRequiredMixin, AdminView):
    login_url = ADMIN_LOGIN_URL

    def get(self, request, specimen_id):
        context = self.get_context_data()
        try:
            specimen = Specimen.objects.get(id=specimen_id)
        except Specimen.DoesNotExist:
            return redirect("admin:specimens")

        specimen.delete()
        specimens = Specimen.objects.all()
        context["specimens"] = specimens
        context["entetes"] = ["Localisation", "État", "Signalement"]
        context["menu"] = "specimens"
        context["supprimer"] = True
        context["id"] = specimen_id
        return render(request, ADMIN_BASE + "specimens.html", context)


class MessagesView(LoginRequiredMixin, AdminView):
    login_url = ADMIN_LOGIN_URL

    def get(self, request):
        context = self.get_context_data()
        context["entetes"] = ["Date", "Expéditeur", "Sujet"]
        context["messages"] = messages_utilisateur(request.user.email)
        context["menu"] = "messages"
        return render(request, ADMIN_BASE + "messages.html", context)


class DetailsMessageView(LoginRequiredMixin, AdminView):
    login_url = ADMIN_LOGIN_URL

    def get(self, request, message_id):
        context = self.get_context_data()
        try:
            message = Message.objects.get(id=message_id)
        except Message.DoesNotExist:
            return redirect("admin:messages")

        context["message"] = message
        context["menu"] = "messages"
        return render(request, ADMIN_BASE + "details_message.html", context)


class ReponseMessageView(LoginRequiredMixin, AdminView):
    login_url = ADMIN_LOGIN_URL
    form_class = MessageForm
    initial = {}

    def post(self, request, message_id):
        form = self.form_class(request.POST)
        if form.is_valid():
            try:
                message_original = Message.objects.get(id=message_id)
            except Message.DoesNotExist:
                return redirect("admin:messages")

            envoyer_message(message_original.receveur, message_original.expediteur,
                            form.cleaned_data["sujet"],
                            form.cleaned_data["message"])
            form = self.form_class(initial=self.initial)
            context = self.get_context_data()
            context["message"] = message_original
            context["form"] = form
            context["reussite"] = True
            return render(
                request, ADMIN_BASE + "reponse_message.html", context)

    def get(self, request, message_id):
        context = self.get_context_data()
        try:
            message = Message.objects.get(id=message_id)
        except Message.DoesNotExist:
            return redirect("admin:messages")

        self.initial["sujet"] = message.sujet
        form = self.form_class(initial=self.initial)
        context["form"] = form
        context["message"] = message
        context["menu"] = "messages"
        return render(request, ADMIN_BASE + "reponse_message.html", context)


class SignalementsView(LoginRequiredMixin, AdminView):
    login_url = ADMIN_LOGIN_URL

    def get(self, request):
        context = self.get_context_data()
        self._fill_context(context)
        return render(request, ADMIN_BASE + "signalements.html", context)

    def _fill_context(self, context):
        entetes = ["Date", "Localisation", "État", "# Spécimen"]
        context["entetes"] = entetes
        context["signalements"] =\
            list(Signalement.objects.all().order_by("-date"))
        context["menu"] = "signalements"


class DetailsSignalementView(LoginRequiredMixin, AdminView):
    login_url = ADMIN_LOGIN_URL

    def get(self, request, signalement_id):
        context = self.get_context_data()
        self._fill_context(context, signalement_id)
        return render(request, ADMIN_BASE + "details_signalement.html", context)

    def _fill_context(self, context, signalement_id):
        try:

sosfrene_admin/templates/sosfrene_admin/activite.html
{% extends "sosfrene_admin/base.html" %}
{% load static %}

{% block titre %} S.O.S Frêne - Ville de Montréal - Nouvelle activité {% endblock %}

{% block contenu %}

    <div class="row">
        <div class="col-md-12 col-xs-12">
            {% if reussite %}
            <div class="alert alert-success fade in" role="alert">
                L'activité a été enregistré.
                <button type="button" class="close" data-dismiss="alert" aria-label="Fermer">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% elif erreur %}
            <div class="alert alert-danger fade in" role="alert">
                Une erreur est survenue pendant l'enregistrement.
                <button type="button" class="close" data-dismiss="alert" aria-label="Fermer">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endif %}
        </div>
    </div>

    <div class="row">
        <div class="col-md-12 col-xs-12">
            <ul class="breadcrumb">
                <li><a href="{%  url route_base|add:'specimens' %}">Spécimens</a></li>
                <li><a href="{%  url route_base|add:'details_specimen' specimen.id %}">{{ specimen.id }}</a></li>
                <li class="active">Nouvelle activité</li>
            </ul>

            <h2>Nouvelle activité</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 col-xs-12">
        {% load crispy_forms_tags %}
        {% crispy form %}
        </div>
    </div>

{% endblock %}

sosfrene_admin/templates/sosfrene_admin/administrateurs.html
{% extends "sosfrene_admin/base.html" %}

{% block titre %} S.O.S Frêne - Ville de Montréal - Gestion des administrateurs {% endblock %}

{% block contenu %}

    <div class="row marge-haut">
        <div class="col-md-12 col-xs-12">
            <h2>Gestion des administrateurs</h2>
            <p>Cette page n'est pas encore disponible.</p>
        </div>
    </div>

{% endblock %}

sosfrene_admin/templates/sosfrene_admin/base.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% load static %}
    <title>{% block titre %}{% endblock %}</title>

    {% block styles %}
    <link href="{% static 'css/app.css' %}" rel="stylesheet">
    {% endblock %}
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <a class="navbar-brand" href="/admin">
                <img class="logo" src="{% static 'img/logo.png'%}">
            </a>

            {% if user.is_authenticated %}
            <a href="#" class="dropdown-toggle visible-xs item-mobile navbar-brand" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user-circle fa-2x" aria-hidden="true"></i></a>
                {% include menu_utilisateur %}
            {% else %}
            <a class="navbar-brand visible-xs item-mobile" href="{% url 'admin:connexion' %}"><i class="fa fa-sign-in" aria-hidden="true"></i> Se connecter</a>
            {% endif %}

            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#menu-collapse" aria-expanded="false" aria-controls=".navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>

            <div id="menu-collapse" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li{% if menu == "tableau" %} class="active" {% endif %}><a href="{% url 'admin:tableau_bord' %}">Tableau de bord</a></li>
                    <li{% if menu == "signalements" %} class="active" {% endif %}><a href="{% url 'admin:signalements' %}">Signalements</a></li>
                    <li{% if menu == "specimens" %} class="active" {% endif %}><a href="{% url 'admin:specimens' %}">Spécimens</a></li>
                    <li{% if menu == "messages" %} class="active" {% endif %}><a href="{% url 'admin:messages' %}">Messages</a></li>
                    <li{% if menu == "gestion" %} class="active" {% endif %}><a href="{% url 'admin:gestion' %}">Administrateurs</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li class="dropdown hidden-xs">
                        <a href="#" class="dropdown-toggle hidden-xs" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ user.get_full_name }} <span class="caret"></span></a>
                        {% include menu_utilisateur %}
                    </li>
                    {% else %}
                    <li class="hidden-xs"><a href="{% url 'admin:connexion' %}"><i class="fa fa-sign-in" aria-hidden="true"></i> Se connecter</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    {% block conteneur %}
    <div class="conteneur-principal">
        {% block contenu %}
        {% endblock %}
    </div>
    {% endblock %}

    {% block pied-de-page %}
    <footer>
        <div class="conteneur-footer-gauche">
            <p>Tous droits réservés. S.O.S&nbsp;Frêne&nbsp;&copy;&nbsp;2017</p>
        </div>
        <div class="conteneur-footer-droite">
            <a class="lien-inverse" href="/contact">Contact</a>
        </div>
    </footer>
    {% endblock %}

    {% block scripts %}
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/bootstrap-notify.min.js' %}"></script>
    <script src="{% static 'js/alert-options.js' %}"></script>
    {% endblock %}
</body>
</html>

sosfrene_admin/templates/sosfrene_admin/connexion.html
{% extends "connexion.html" %}

{% block entete %}
    <h3>Connexion des adminstrateurs</h3>
{% endblock %}
{% block client %}
{% endblock %}

sosfrene_admin/templates/sosfrene_admin/details_message.html
{% extends "sosfrene_admin/base.html" %}
{% load static %}

{% block titre %} S.O.S Frêne - Ville de Montréal - Détails du message {% endblock %}

{% block contenu %}

{% include "sosfrene_core/details_message.html"%}

{% endblock %}

sosfrene_admin/templates/sosfrene_admin/details_signalement.html
{% extends "sosfrene_admin/base.html" %}
{% load static %}

{% block titre %} S.O.S Frêne - Ville de Montréal - Détails du signalement {% endblock %}

{% block contenu %}

    <div class="row">
        <div class="col-md-12 col-xs-12">
            {% block navigation %}
            <ul class="breadcrumb">
                <li><a href="{% url 'admin:signalements' %}">Signalements</a></li>
                <li class="active">{{ signalement.id }}</li>
            </ul>
            {% endblock %}

            {% if not signalement.accepte %}
                <a id="btn-traiter-signalement" href="/admin/signalements/{{ signalement.id }}/traitement" class="btn btn-primary btn-large">Traiter</a>
            {% endif %}
            <h2>Détails du signalement</h2>

            <fieldset>
                <legend>Informations</legend>
                {% if signalement.accepte %}
                    <label>État: traité</label>
                {% else %}
                    <label>État: En attente</label>
                {% endif %}

                <br>
                <label>Date d'envoi: {{ signalement.date|date:"Y/m/d" }}</label>
                <br>
                <label>Votre description:</label>
                <p><em>{{ signalement.description }}</em></p>
            </fieldset>

            <fieldset>
                <legend>Photos</legend>
                {% for photo in photos %}
                    <a href="{{ photo.source.url }}">
                        <img class="image-signalement" src="{{ photo.source.url }}">
                    </a>
                {% endfor %}
            </fieldset>
        </div>
    </div>

{% endblock %}

sosfrene_admin/templates/sosfrene_admin/menu.html
<ul class="dropdown-menu">
    <li><a href="{% url 'admin:deconnexion' %}"><i class="fa fa-sign-out" aria-hidden="true"></i> Déconnexion</a></li>
</ul>

sosfrene_admin/templates/sosfrene_admin/specimens.html
{% extends "sosfrene_admin/base.html" %}
{% load static %}

{% block titre %} S.O.S Frêne - Ville de Montréal - Spécimens {% endblock %}

{% block styles %}
    {{ block.super }}
    <link href="{% static 'css/buttons.css' %}" rel="stylesheet">
{% endblock %}

{% block contenu %}

    <div class="row">
        <div class="col-md-12 col-xs-12">
            {% if supprimer %}
            <div class="alert alert-success fade in" role="alert">
                Le spécimen numéro {{ id }} a été supprimé.
                <button type="button" class="close" data-dismiss="alert" aria-label="Fermer">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endif %}

            <ul class="breadcrumb">
                <li class="active">Spécimens</li>
            </ul>

            <h2>Spécimens</h2>

            <table class="table table-striped">
                <thead>
                    <tr>
                    {% for entete in entetes %}
                        <th>{{entete}}</th>
                    {% endfor %}
                    </tr>
                </thead>
                <tbody>
                {% for specimen in specimens %}
                    <tr>
                        <td>{{ specimen.localisation.latitude|floatformat:5 }}
                            <br>
                            {{ specimen.localisation.longitude|floatformat:5 }}
                        </td>
                        <td>{{ specimen.etat }}</td>
                        {% if specimen.signalement.get %}
                            <td>{{ specimen.signalement.get.id }}</td>
                        {% else %}
                            <td>Aucun</td>
                        {% endif %}
                        <td>
                            <a href="{% url route_base|add:'details_specimen' specimen.id %}" class="btn btn-default">
                                <i class="fa fa-info"></i> Détails
                            </a>
                            <a href="{% url route_base|add:'supprimer_specimen' specimen.id %}" class="btn btn-default">
                                <i class="fa fa-remove"></i> Supprimer
                            </a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <a href="{% url 'admin:nouveau_specimen' %}" class="button btn-primaire button-circle button-jumbo flottant">
        <i style="color: #fff;" class="fa fa-plus"></i>
    </a>

{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script src="{% static 'js/ouvrir_lien.js' %}"></script>
{% endblock %}

sosfrene_admin/templates/sosfrene_admin/traiter_signalement.html
{% extends "sosfrene_admin/base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block titre %} S.O.S Frêne - Ville de Montréal - Traitement du signalement {% endblock %}

{% block contenu %}

    <div class="row">
        <div class="col-md-12 col-xs-12">
            <ul class="breadcrumb">
                <li><a href="{% url 'admin:signalements' %}">Signalements</a></li>
                <li><a href="/admin/signalements/{{ signalement.id }}">{{ signalement.id }}</a></li>
                <li class="active">Traitement</li>
            </ul>

            {% if traiter %}
            <div class="alert alert-success fade in" role="alert">
                Le traitement du signalement a été enregistré.
                <button type="button" class="close" data-dismiss="alert" aria-label="Fermer">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% else %}
            <h2>Traitement du signalement</h2>

            <div class="row">
                <form id="form-traitement" action="{% url 'admin:traiter_signalement' signalement.id  %}" method="post">
                {% csrf_token %}
                {{ form.statut_specimen|attr:"id:statut-specimen" }}
                    <div class="col-md-7 col-xs-12">
                        <fieldset>
                            <legend>Informations</legend>
                            <label>Date d'envoi: {{ signalement.date|date:"Y/m/d" }}</label>
                            <br>
                            <label>Soumis par: {{ utilisateur.user.get_full_name }}</label>
                            <br>
                            <label>Message pour l'utilisateur:</label>
                            <br>
                            <div id="conteneur-message" class="form-group has-feedback">
                                {{ form.message|attr:"cols:40"|attr:"rows:10"|attr:"id:ta-message"|add_class:"textarea form-control" }}
                                <span class="help-block invisible">Vous devez entrer un message.</span>
                            </div>
                        </fieldset>
                        <br>
                    </div>
                    <div class="col-md-5 col-xs-12">
                        <fieldset id="fs-specimen">
                            <legend>Détails du spécimen</legend>
                            <label>Latitude: {{ signalement.localisation.latitude }}</label>
                            <br>
                            <label>Longitude: {{ signalement.localisation.longitude }}</label>
                            <br>
                            <label>État: atteint</label>
                            <br>

                            <label id="label-statut">Statut: à confirmer</label>
                        </fieldset>
                        <br>
                        <button type="button" id="btn-confirmer-specimen" class="btn btn-default">Confirmer le spécimen</button>
                    </div>
            </div>
                <hr>
                <button id="btn-soumettre-traitement" type="button" class="btn btn-primary btn-large">Soumettre</button>
                </form>
            {% endif %}
        </div>
    </div>

{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script src="{% static 'js/traiter_signalement.js' %}"></script>
{% endblock %}