sosfrene_client/urls.py
"""
    Les routes
"""
from django.conf.urls import url

from sosfrene_client.views import (
    EnregistrementView, DeconnexionView, ConnexionView,
    SignalementsView, DetailsSignalementView, NouveauSignalementView,
    MessagesView, DetailsMessageView, ReponseMessageView, ProfilView,
    TelechargementView, AccueilView, CarteView, FreneView, AgrileView,
    SymptomesView, SpecimensCarteView, NotificationsView,
    ArchiverNotificationView
)

urlpatterns = [
    url(r'^$', AccueilView.as_view(), name="accueil"),
    url(r'^carte/$', CarteView.as_view(), name="carte"),
    url(r'^specimens-carte/$', SpecimensCarteView.as_view(),
        name="specimens-carte"),
    url(r'^frene/$', FreneView.as_view(), name="frene"),
    url(r'^agrile/$', AgrileView.as_view(), name="agrile"),
    url(r'^symptomes/$', SymptomesView.as_view(), name="symptomes"),
    url(r'^enregistrement/$', EnregistrementView.as_view(),
        name="enregistrement"),
    url(r'^connexion/$', ConnexionView.as_view(), name="connexion"),
    url(r'^deconnexion/$', DeconnexionView.as_view(), name="deconnexion"),
    url(r'^notifications/$', NotificationsView.as_view(),
        name="notifications"),
    url(r'^archiver-notifications/$',
        ArchiverNotificationView.as_view(), name="archiver_notification"),
    url(r'^signalements/$', SignalementsView.as_view(), name="signalements"),
    url(r'^signalements/nouveau/$', NouveauSignalementView.as_view(),
        name="nouveau_signalement"),
    url(r'^signalements/(?P<signalement_id>[0-9]+)/$',
        DetailsSignalementView.as_view(), name="detailssignalement"),
    url(r'^messages/$', MessagesView.as_view(), name="messages"),
    url(r'^messages/(?P<message_id>[0-9]+)/$',
        DetailsMessageView.as_view(), name="details_message"),
    url(r'^messages/(?P<message_id>[0-9]+)/reponse/$',
        ReponseMessageView.as_view(), name="reponse"),
    url(r'^profil/$', ProfilView.as_view(), name="profil"),
    url(r'^telechargement/$', TelechargementView.as_view(),
        name="telechargement")
]

sosfrene_core/urls.py
"""
    Les routes
"""
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^admin/', include("sosfrene_admin.urls",
                            namespace="admin")),
    url(r'^', include("sosfrene_client.urls",
                       namespace="client")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sosfrene_client/forms.py
from django import forms
from django.core.exceptions import ValidationError

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout

from sosfrene_core.api import courriel_existe


class SpanRequiredForm(forms.Form):
    def clean_required(self, field_data, message="Ce champ est requis."):
        if field_data is None:
            raise ValidationError(message)


class EnregistrementForm(SpanRequiredForm):
    first_name = forms.CharField(label="Prénom", max_length=80, required=False)
    last_name = forms.CharField(label="Nom", max_length=80, required=False)
    email = forms.EmailField(label="Courriel", max_length=80, required=False)
    password = forms.CharField(label="Mot de passe", widget=forms.PasswordInput,
                               max_length=80, required=False)
    confirm_password = forms.CharField(
        label="Confirmez votre mot de passe",
        widget=forms.PasswordInput,
        max_length=80, required=False)

    def __init__(self, *args, **kwargs):
        super(EnregistrementForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'form-enregistrement'
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Créer un compte', css_class="btn-block"))
        self.helper.error_text_inline = False

    def clean_first_name(self):
        self.clean_required(self.cleaned_data["first_name"])
        return self.cleaned_data["first_name"]

    def clean_last_name(self):
        self.clean_required(self.cleaned_data["last_name"])
        return self.cleaned_data["last_name"]

    def clean_email(self):
        self.clean_required(self.cleaned_data["email"])
        if courriel_existe(self.cleaned_data["email"]):
            raise ValidationError("Cette adresse courriel est déjà utilisée.")
        return self.cleaned_data["email"]

    def clean_password(self):
        self.clean_required(self.cleaned_data["password"])
        return self.cleaned_data["password"]

    def clean_confirm_password(self):
        self.clean_required(self.cleaned_data["confirm_password"])

        if self.cleaned_data["password"] !=\
                self.cleaned_data["confirm_password"]:
            raise ValidationError('Les mots de passe doivent être identiques.')

        return self.cleaned_data["confirm_password"]


class ConnexionForm(SpanRequiredForm):
    email = forms.EmailField(label="Courriel", max_length=80, required=False)
    password = forms.CharField(label="Mot de passe", widget=forms.PasswordInput,
                               max_length=80, required=False)

    def __init__(self, *args, **kwargs):
        super(ConnexionForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'form-connexion'
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Se connecter', css_class="btn-block"))
        self.helper.error_text_inline = False

    def clean_email(self):
        self.clean_required(self.cleaned_data["email"])
        if not courriel_existe(self.cleaned_data["email"]):
            raise ValidationError(
                "Aucun utilisateur avec cette adresse n'a été trouvé.")
        return self.cleaned_data["email"]

    def clean_password(self):
        self.clean_required(self.cleaned_data["password"])
        return self.cleaned_data["password"]


class SignalementForm(SpanRequiredForm):
    description = forms.CharField(
        widget=forms.Textarea, label="Description", max_length=500, required=False)
    longitude = forms.FloatField(widget=forms.HiddenInput())
    latitude = forms.FloatField(widget=forms.HiddenInput())
    photos_pks = forms.CharField(widget=forms.HiddenInput())

    def __init__(self, *args, **kwargs):
        super(SignalementForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'form-nouveau-signalement'
        self.helper.form_method = 'post'
        self.helper.error_text_inline = False
        self.helper.layout = Layout(
            "longitude", "latitude", "photos_pks", "description")


class TraiterSignalementForm(forms.Form):
    statut_specimen = forms.CharField(
        widget=forms.HiddenInput(), required=False)
    message = forms.CharField(
        widget=forms.Textarea, label="Message pour l'utilisateur:",
        max_length=1000, required=False)


class MessageForm(SpanRequiredForm):
    sujet = forms.CharField(label="Sujet", max_length=80)
    message = forms.CharField(
        widget=forms.Textarea, label="Votre message:",
        max_length=1000, required=False)

    def clean_message(self):
        self.clean_required(self.cleaned_data["message"])
        return self.cleaned_data["message"]

    def clean_sujet(self):
        self.clean_required(self.cleaned_data["sujet"])
        return self.cleaned_data["sujet"]


class ProfilForm(forms.Form):
    notifications = forms.BooleanField(
        label="Recevoir les notifications par courriel", required=False)

    def __init__(self, *args, **kwargs):
        super(ProfilForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'form-profil'
        self.helper.form_method = 'post'
        self.helper.add_input(Submit(
            'submit', 'Enregistrer', css_id="btn-enregistrer-profil"))

sosfrene_client/views.py
import json
from django.views import View
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.utils import timezone
from django.utils.timezone import now

from sosfrene_client.forms import (
    EnregistrementForm, ConnexionForm, SignalementForm, ProfilForm, MessageForm
)
from sosfrene_core.models import (
    Utilisateur, Photo, Message, Signalement,
    DetailSignalement, Localisation, Notification
)
from sosfrene_core.api import (
    signalements_utilisateur, messages_utilisateur,
    specimens_carte, notifications_utilisateur, creer_signalement
)


class ClientView(View):

    def get_context_data(self):
        context = {}
        context["menu_utilisateur"] = "sosfrene_client/menu.html"
        context["route_base"] = "client:"
        return context


class AccueilView(ClientView):

    def get(self, request):
        context = self.get_context_data()
        return render(request, "accueil.html", context)


class CarteView(ClientView):

    def get(self, request):
        context = self.get_context_data()
        context["menu"] = "carte"
        return render(request, "carte.html", context)


class FreneView(ClientView):

    def get(self, request):
        context = self.get_context_data()
        context["menu"] = "frene"
        return render(request, "frene.html", context)


class AgrileView(ClientView):

    def get(self, request):
        context = self.get_context_data()
        context["menu"] = "agrile"
        return render(request, "agrile.html", context)


class SymptomesView(ClientView):

    def get(self, request):
        context = self.get_context_data()
        context["menu"] = "symptomes"
        return render(request, "symptomes.html", context)


class EnregistrementView(ClientView):
    form_class = EnregistrementForm
    initial = {}

    def get(self, request):
        if request.user.is_authenticated():
            return redirect("client:accueil")

        form = self.form_class(initial=self.initial)
        context = {}
        context["form"] = form
        return render(request, "enregistrement.html", context)

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            try:
                user = User.objects.create_user(
                    form.cleaned_data["email"],
                    password=form.cleaned_data["password"])
                nouvel_utilisateur = Utilisateur()
                user.first_name = form.cleaned_data["first_name"]
                user.last_name = form.cleaned_data["last_name"]
                user.email = form.cleaned_data["email"]
                user.save()
                nouvel_utilisateur.user = user
                nouvel_utilisateur.notifications = False
                nouvel_utilisateur.save()
            except Exception:
                return render(
                    request, "enregistrement.html",
                    {'form': form, "erreur": True})

            form = self.form_class(initial=self.initial)
            return render(request, "enregistrement.html",
                          {'form': form, "reussite": True})
        return render(
            request, "enregistrement.html", {'form': form})


class ConnexionView(View):
    form_class = ConnexionForm
    initial = {}

    def get(self, request):
        if request.user.is_authenticated():
            return redirect("client:notifications")

        form = self.form_class(initial=self.initial)
        context = {}
        context["form"] = form
        return render(request, "connexion.html", context)

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = authenticate(username=form.cleaned_data["email"],
                                password=form.cleaned_data["password"])
            if user is not None:
                login(request, user)
                return redirect("client:notifications")
            else:
                return render(request, "connexion.html",
                              {'form': form, "erreur_mdp": True})

        return render(request, "connexion.html", {'form': form})


class DeconnexionView(View):
    def get(self, request):
        logout(request)
        return redirect("client:accueil")


class SignalementsView(LoginRequiredMixin, ClientView):

    def get(self, request):
        context = self.get_context_data()
        context["menu"] = "signalements"
        self._fill_context(context, request.user)
        return render(request, "signalements.html", context)

    def _fill_context(self, context, user):
        entetes = ["Date", "Localisation", "État", "# Spécimen"]
        context["entetes"] = entetes
        context["signalements"] = signalements_utilisateur(user)

class DetailsSignalementView(LoginRequiredMixin, ClientView):

    def get(self, request, signalement_id):
        context = self.get_context_data()
        context["menu"] = "signalements"
        self._fill_context(context, signalement_id)
        if context["signalement"]:
            return render(
                request, "details_signalement.html", context)
        else:
            return redirect("client:signalements")

    def _fill_context(self, context, signalement_id):
        try:
            signalement = Signalement.objects.get(id=signalement_id)
            context["signalement"] = signalement
            photos = Photo.objects.filter(
                detailsignalement__signalement=signalement)
            context["photos"] = photos
        except Signalement.DoesNotExist:
            context["signalement"] = None


class NouveauSignalementView(LoginRequiredMixin, ClientView):
    form_class = SignalementForm
    initial = {"date": timezone.now()}

    def get(self, request):
        form = self.form_class(initial=self.initial)
        context = self.get_context_data()
        context["menu"] = "signalements"
        context["form"] = form
        return render(
            request, "nouveau_signalement.html", context)

    def post(self, request):
        form = self.form_class(request.POST)
        context = self.get_context_data()
        context["menu"] = "signalements"
        context["form"] = form
        if form.is_valid():
            try:
                creer_signalement(
                    form.cleaned_data["latitude"], form.cleaned_data["longitude"],
                    form.cleaned_data["description"], request.user,
                    form.cleaned_data["photos_pks"])

                form = self.form_class(initial=self.initial)
                context["form"] = form
                context["reussite"] = True
                return render(
                    request, "nouveau_signalement.html",
                    context)
            except Exception:
                context["erreur"] = True
                return render(
                    request, "nouveau_signalement.html",
                    context)
        else:
            render(request, "nouveau_signalement.html",
                   context)


class MessagesView(LoginRequiredMixin, ClientView):

    def get(self, request):
        context = self.get_context_data()
        context["menu"] = "messages"
        context["entetes"] = ["Date", "Expéditeur", "Sujet"]
        context["messages"] = messages_utilisateur(request.user.email)
        return render(request, "messages.html", context)


class DetailsMessageView(LoginRequiredMixin, ClientView):

    def get(self, request, message_id):
        context = self.get_context_data()
        context["menu"] = "messages"
        try:
            message = Message.objects.get(id=message_id)
        except Message.DoesNotExist:
            return redirect("client:messages")

        context["message"] = message
        return render(request, "details_message.html", context)


class ReponseMessageView(LoginRequiredMixin, ClientView):
    form_class = MessageForm
    initial = {}

    def post(self, request, message_id):
        form = self.form_class(request.POST)
        if form.is_valid():
            message_original = Message.objects.get(id=message_id)
            contenu = form.cleaned_data["message"]
            nouveau_message = Message()
            nouveau_message.contenu = contenu
            nouveau_message.expediteur = message_original.receveur
            nouveau_message.receveur = message_original.expediteur
            nouveau_message.sujet = form.cleaned_data["sujet"]
            nouveau_message.date = now()
            nouveau_message.save()
            form = self.form_class(initial=self.initial)
            context = self.get_context_data()
            context["message"] = message_original
            context["form"] = form
            context["reussite"] = True
            return render(
                request, "reponse_message.html", context)

    def get(self, request, message_id):
        context = self.get_context_data()
        context["menu"] = "messages"
        try:
            message = Message.objects.get(id=message_id)
        except Message.DoesNotExist:
            return redirect("client:messages")

        self.initial["sujet"] = message.sujet
        form = self.form_class(initial=self.initial)
        context["form"] = form
        context["message"] = message
        return render(request, "reponse_message.html", context)


class ProfilView(LoginRequiredMixin, ClientView):
    form_class = ProfilForm
    initial = {}

    def get(self, request):
        self._remplir_initial(request.user)
        form = self.form_class(initial=self.initial)
        context = self.get_context_data()
        context["menu"] = "profil"
        context["form"] = form
        context["user"] = request.user
        return render(request, "profil.html", context)

    def post(self, request):

sosfrene_client/templates/sosfrene_client/accueil.html
{% extends "base.html" %}

{% block titre %} S.O.S Frêne - Ville de Montréal - Accueil {% endblock %}

{% block contenu %}

    <div class="row">
        <div class="col-md-12 col-sm-12">
            <div id="caroussel" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarousel" data-slide-to="1"></li>
                    <li data-target="#myCarousel" data-slide-to="2"></li>
                </ol>

                <div class="carousel-caption">
                    <h1>S.O.S Frêne</h1>
                </div>

                <div class="carousel-inner">
                    <div class="item active">
                        <div class="overlay"></div>
                        <img src="static/img/caroussel01.jpg">
                    </div>
                    <div class="item">
                        <div class="overlay"></div>
                        <img src="static/img/caroussel02.jpg">
                    </div>
                    <div class="item">
                        <div class="overlay"></div>
                        <img src="static/img/caroussel03.jpg">
                    </div>
                </div>

                <a class="left carousel-control" href="#caroussel" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#caroussel" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
    </div>
    <div class="row marge-haut">
        <div class="col-md-12 col-xs-12">
            <h2>Mission</h2>
            <p>
            <em>S.O.S Frêne</em> est un programme pour les citoyens mis en place par la Ville de Montréal dans le cadre
            de la lutte contre l'agrile du frêne, un petit insecte ravageur originaire d'Asie, qui s'attaque à l'écorce
            de toutes les espèces de frêne présentes sur notre territoire. En créant une plate-forme d'échange entre
            les citoyens et les employés de la Ville, l'administration souhaite améliorer la gestion de l'épidémie.
            L'inscription est gratuite. Créez votre compte dès maintenant!</p>

            {% if not user.is_authenticated %}
            <a href="{% url 'client:enregistrement' %}" class="btn btn-lg btn-default">Inscrivez-vous</a>
            {% endif %}

        </div>
    </div>

{% endblock %}

sosfrene_client/templates/sosfrene_client/agrile.html
{% extends "base.html" %}

{% block titre %} S.O.S Frêne - Ville de Montréal - Le frêne {% endblock %}

{% block contenu %}

    <div class="row marge-haut">
        <div class="col-md-12 col-xs-12">
            <h2>L'agrile</h2>
            <h3>Identification de l'agrile du frêne</h3>
            <p>Les adultes sont vert métallique sur le dessus et vert émeraude en-dessous. Du fait de leur taille relativement modeste
                (8,5 à 14,0 mm de longueur sur 3,1 à 3,4 mm de largeur), ils sont difficiles à détecter, et il est souvent plus
                 facile de repérer les galeries sinueuses forées par les larves ou les frênes infestés que l'insecte lui-même.
            </p>
        </div>
    </div>

{% endblock %}

sosfrene_client/templates/sosfrene_client/base.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% load static %}
    <title>{% block titre %}{% endblock %}</title>

    {% block styles %}
    <link href="{% static 'css/app.css' %}" rel="stylesheet">
    {% endblock %}
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">
                <img class="logo" src="{% static 'img/logo.png'%}">
            </a>

            {% if user.is_authenticated %}
            <a href="#" class="dropdown-toggle visible-xs item-mobile navbar-brand" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <i class="fa fa-user-circle fa-2x" aria-hidden="true"><div id="notification-mobile" class="nombre-notification invisible"></div></i>
            </a>
                {% include menu_utilisateur %}
            {% else %}
            <a class="navbar-brand visible-xs item-mobile" href="{% url 'client:connexion' %}"><i class="fa fa-sign-in" aria-hidden="true"></i> Se connecter</a>
            {% endif %}

            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#menu-collapse" aria-expanded="false" aria-controls=".navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>

            <div id="menu-collapse" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li {% if menu == "carte" %} class="active" {% endif %}><a href="{% url 'client:carte' %}"><i class="fa fa-map" aria-hidden="true"></i> Carte</a></li>
                    <li {% if menu == "frene" %} class="active" {% endif %}><a href="{% url 'client:frene' %}"><i class="fa fa-pagelines" aria-hidden="true"></i> Le frêne</a></li>
                    <li {% if menu == "agrile" %} class="active" {% endif %}><a href="{% url 'client:agrile' %}"><i class="fa fa-bug" aria-hidden="true"></i> L'agrile</a></li>
                    <li {% if menu == "symptomes" %} class="active" {% endif %}><a href="{% url 'client:symptomes' %}"><i class="fa fa-medkit" aria-hidden="true"></i> Les symptômes</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li class="dropdown hidden-xs">
                        <a href="#" class="dropdown-toggle hidden-xs" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            {{ user.get_full_name }} <span class="caret"></span>
                            <div id="notification-desktop" class="nombre-notification-desktop invisible"></div>
                        </a>
                        {% include menu_utilisateur %}
                    </li>
                    {% else %}
                    <li class="hidden-xs"><a href="{% url 'client:connexion' %}"><i class="fa fa-sign-in" aria-hidden="true"></i> Se connecter</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    {% block conteneur %}
    <div class="conteneur-principal">
        {% block contenu %}
        {% endblock %}
    </div>
    {% endblock %}

    {% block pied-de-page %}
    <footer>
        <div class="conteneur-footer-gauche">
            <p>Tous droits réservés. S.O.S&nbsp;Frêne&nbsp;&copy;&nbsp;2017</p>
        </div>
        <div class="conteneur-footer-droite">
            <a class="lien-inverse" href="/contact">Contact</a>
        </div>
    </footer>
    {% endblock %}

    {% block scripts %}
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/loadingoverlay.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/bootstrap-notify.min.js' %}"></script>
    <script src="{% static 'js/alert-options.js' %}"></script>
    {% endblock %}
</body>
</html>

sosfrene_client/templates/sosfrene_client/carte.html
{% extends "base.html" %}
{% load static %}

{% block titre %} S.O.S Frêne - Ville de Montréal - Le frêne {% endblock %}

{% block contenu %}

    <div class="row marge-haut">
        <div class="col-md-12 col-xs-12">
            <h2>Spécimens répertoriés</h2>
            <div id="map"></div>
        </div>
    </div>

{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCjfCx9tnmDutlM2UNb0tVBDL6K5ZNfteo&callback=initMap">
    </script>
    <script src="{% static 'js/sosfrene_client/carte.js' %}"></script>
{% endblock %}

sosfrene_client/templates/sosfrene_client/connexion.html
{% extends "base.html" %}

{% block titre %} S.O.S Frêne - Ville de Montréal - Connexion {% endblock %}

{% block conteneur %}
    <div class="conteneur-principal-centre">
        <div class="conteneur-centre">
            {% if erreur_mdp %}
            <div class="alert alert-danger" role="alert">
                Le mot de passe n'est pas valide.
            </div>
            {% endif %}
            {% block entete %}
            <h3>Connexion</h3>
            {% endblock %}
            {% load crispy_forms_tags %}
            {% crispy form %}
            {% block client %}
            <p>Vous n'avez pas de compte?<br> <a href="{% url 'client:enregistrement' %}">Inscrivez-vous</a> dès maintenant.</p>
            {% endblock %}
        </div>
    </div>
{% endblock %}

sosfrene_client/templates/sosfrene_client/details_message.html
{% extends "base.html" %}
{% load static %}

{% block titre %} S.O.S Frêne - Ville de Montréal - Détails du message {% endblock %}

{% block contenu %}

{% include "sosfrene_core/details_message.html"%}

{% endblock %}

sosfrene_client/templates/sosfrene_client/details_signalement.html
{% extends "base.html" %}
{% load static %}

{% block titre %} S.O.S Frêne - Ville de Montréal - Détails du signalement {% endblock %}

{% block contenu %}

    <div class="row">
        <div class="col-md-12 col-xs-12">
            {% block navigation %}
            <ul class="breadcrumb">
                <li><a href="{% url 'client:signalements' %}">Signalements</a></li>
                <li class="active">{{ signalement.id }}</li>
            </ul>
            {% endblock %}

            {% block admin %}
            {% endblock %}
            <h2>Détails du signalement</h2>

            <fieldset>
                <legend>Informations</legend>
                {% if signalement.accepte %}
                    <label>État: traité</label>
                {% else %}
                    <label>État: En attente</label>
                {% endif %}

                <br>
                <label>Date d'envoi: {{ signalement.date|date:"Y/m/d" }}</label>
                <br>
                <label>Votre description:</label>
                <p><em>{{ signalement.description }}</em></p>
            </fieldset>

            <fieldset>
                <legend>Photos</legend>
                {% for photo in photos %}
                    <a href="{{ photo.source.url }}">
                        <img class="image-signalement" src="{{ photo.source.url }}">
                    </a>
                {% endfor %}
            </fieldset>
        </div>
    </div>

{% endblock %}

sosfrene_client/templates/sosfrene_client/enregistrement.html
{% extends "base.html" %}

{% block titre %} S.O.S Frêne - Ville de Montréal - Inscription {% endblock %}

{% block conteneur %}
    <div class="conteneur-principal-centre">
        <div class="conteneur-centre">
            {% if erreur %}
            <div class="alert alert-danger" role="alert">
                Une erreur est survenue lors de la création de votre compte. Veuillez
                rééssayer ou nous contacter par courriel.
            </div>
            {% endif %}
            {% if reussite %}
            <div class="alert alert-success" role="alert">
                Votre compte a été créé avec succès. Vous pouvez maintenant vous connecter.
            </div>
            {% endif %}
            <h3>Inscription au service</h3>
            <p>Afin de pouvoir participer à notre plateforme, il suffit de remplir le formulaire suivant pour créer
                votre compte.</p>
            {% load crispy_forms_tags %}
            {% crispy form %}
        </div>
    </div>
{% endblock %}

sosfrene_client/templates/sosfrene_client/frene.html
{% extends "base.html" %}

{% block titre %} S.O.S Frêne - Ville de Montréal - Le frêne {% endblock %}

{% block contenu %}

    <div class="row marge-haut">
        <div class="col-md-12 col-xs-12">
            <h2>Le frêne</h2>
            <h3>Voici trois façons simples de reconnaître les frênes:</h3>
            <ol>
                <li>Le frêne possède des feuilles composées opposées.</li>
                <li>Ses feuilles sont composées d’un nombre impair (5 à 11) de folioles (petites feuilles dépourvues de pétiole).
                Chaque feuille, et chaque branche, est jumelée à une autre feuille du côté opposé sur les branches de façon symétrique.
                </li>
                <li>Contrairement aux érables à giguère la foliole de l’extrémité d’une feuille de frêne ne comporte pas de dents.</li>
            </ol>
        </div>
    </div>

{% endblock %}

sosfrene_client/templates/sosfrene_client/menu.html
<ul class="dropdown-menu">
    <li><a href="{% url 'client:notifications' %}"><i class="fa fa-bell" aria-hidden="true"></i> Notifications</a></li>
    <li><a href="{% url 'client:signalements' %}"><i class="fa fa-flag" aria-hidden="true"></i> Signalements</a></li>
    <li><a href="{% url 'client:messages' %}"><i class="fa fa-comment" aria-hidden="true"></i> Messages</a></li>
    <li><a href="{% url 'client:profil' %}"><i class="fa fa-user" aria-hidden="true"></i> Mon profil</a></li>
    <li><a href="{% url 'client:deconnexion' %}"><i class="fa fa-sign-out" aria-hidden="true"></i> Déconnexion</a></li>
</ul>